- name: copy mongodb repo
   ansible.builtin.copy:
    src: mongodd.repo
    dest: /etc/yum.repos.s/mongodb.repo

 - name: Install mongodb
   ansible.builtin.package:
    name: mongo-org
    state: present
  
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enable: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: restarted